// ESLint 9 flat config.
// Run via `npm run lint` / `npm run lint:fix`.
//
// Layers we lint:
//   - all src/**/*.{ts,tsx} authored by the team
// Layers we deliberately do NOT lint (excluded below):
//   - routeTree.gen.ts          (auto-generated by TanStack Router)
//   - src/components/ui/**      (shadcn — vendored, leave alone)
//   - src/routeTree.gen.ts      (auto-generated)
//   - src/features/dashboard/** (legacy editor, slated for removal)
//   - .output, dist, build, node_modules

import js from '@eslint/js'
import tseslint from 'typescript-eslint'
import react from 'eslint-plugin-react'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import importX from 'eslint-plugin-import-x'
import jsxA11y from 'eslint-plugin-jsx-a11y'
import prettier from 'eslint-config-prettier'
import globals from 'globals'

export default tseslint.config(
  // ── Ignored paths ──────────────────────────────────────────────
  {
    ignores: [
      'node_modules/**',
      '.output/**',
      '.claude/**', // claude-code worktrees — copies of the source tree
      'dist/**',
      'build/**',
      'public/**',
      '**/*.gen.ts',
      'src/components/ui/**',
      'src/features/dashboard/**',
      'eslint.config.js',
    ],
  },

  // ── Base JS + TypeScript rules ────────────────────────────────
  js.configs.recommended,
  ...tseslint.configs.recommended,

  // ── React hooks flat preset (v7+ ships its own flat config) ──
  reactHooks.configs.flat['recommended-latest'] ?? reactHooks.configs.flat.recommended,

  // ── Project-wide TS / React config ────────────────────────────
  {
    files: ['src/**/*.{ts,tsx}'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      parserOptions: {
        ecmaFeatures: { jsx: true },
      },
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    plugins: {
      react,
      'react-refresh': reactRefresh,
      'import-x': importX,
      'jsx-a11y': jsxA11y,
    },
    settings: {
      react: { version: 'detect' },
    },
    rules: {
      // React
      ...react.configs.recommended.rules,
      ...react.configs['jsx-runtime'].rules, // React 17+ — no need to import React
      'react/prop-types': 'off', // we use TS

      // Vite HMR friendliness
      'react-refresh/only-export-components': ['warn', { allowConstantExport: true }],

      // jsx-a11y — keep recommended on but tone down a few that fire on
      // editor handles (which are intentionally non-keyboard for now).
      ...jsxA11y.configs.recommended.rules,
      'jsx-a11y/click-events-have-key-events': 'off',
      'jsx-a11y/no-static-element-interactions': 'off',

      // TS — relax a few defaults; we can tighten later.
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': [
        'warn',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
      '@typescript-eslint/no-empty-object-type': 'off',
      '@typescript-eslint/consistent-type-imports': ['warn', { fixStyle: 'inline-type-imports' }],

      // Misc quality of life
      'no-console': ['warn', { allow: ['warn', 'error'] }],
      'prefer-const': 'warn',
      'no-debugger': 'warn',

      // ── react-hooks v7 new rules — downgrade noisy ones ──
      // `set-state-in-effect` flags the legitimate "sync local state with
      // an external prop on change" pattern that the React docs themselves
      // bless. Keep it as a warn signal instead of a hard error.
      'react-hooks/set-state-in-effect': 'warn',
      // `immutability` fires false positives on useCallback returns that
      // close over hoisted refs (resize/rotate gestures). Downgrade for now.
      'react-hooks/immutability': 'warn',
    },
  },

  // ── Route files override ─────────────────────────────────────
  // TanStack Router route files MUST export both a Route constant and a
  // component, so react-refresh/only-export-components is structurally
  // impossible to satisfy here. Disable just for routes/.
  {
    files: ['src/routes/**/*.{ts,tsx}'],
    rules: {
      'react-refresh/only-export-components': 'off',
    },
  },

  // ── Layer boundary enforcement ────────────────────────────────
  // ADR-002: schema ← widgets ← renderer ← designer (one-way).
  // Anything that breaks this throws a lint error.
  {
    files: ['src/packages/**/*.{ts,tsx}'],
    plugins: { 'import-x': importX },
    rules: {
      'import-x/no-restricted-paths': [
        'error',
        {
          zones: [
            {
              target: './src/packages/schema',
              from: './src/packages/widgets',
              message: 'schema must not depend on widgets',
            },
            {
              target: './src/packages/schema',
              from: './src/packages/renderer',
              message: 'schema must not depend on renderer',
            },
            {
              target: './src/packages/schema',
              from: './src/packages/designer',
              message: 'schema must not depend on designer',
            },
            {
              target: './src/packages/widgets',
              from: './src/packages/renderer',
              message: 'widgets must not depend on renderer',
            },
            {
              target: './src/packages/widgets',
              from: './src/packages/designer',
              message: 'widgets must not depend on designer',
            },
            {
              target: './src/packages/renderer',
              from: './src/packages/designer',
              message: 'renderer must not depend on designer',
            },
          ],
        },
      ],
    },
  },

  // ── Prettier compat — disable rules that conflict with formatting ──
  // Keep this LAST so it overrides any stylistic rules above.
  prettier,
)
