/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EditorV2RouteImport } from './routes/editor-v2'
import { Route as DesignerRouteImport } from './routes/designer'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutIndexRouteImport } from './routes/layout/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorV2Route = EditorV2RouteImport.update({
  id: '/editor-v2',
  path: '/editor-v2',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerRoute = DesignerRouteImport.update({
  id: '/designer',
  path: '/designer',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/layout/',
  path: '/layout/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/designer': typeof DesignerRoute
  '/editor-v2': typeof EditorV2Route
  '/login': typeof LoginRoute
  '/layout/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/designer': typeof DesignerRoute
  '/editor-v2': typeof EditorV2Route
  '/login': typeof LoginRoute
  '/layout': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/designer': typeof DesignerRoute
  '/editor-v2': typeof EditorV2Route
  '/login': typeof LoginRoute
  '/layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/designer' | '/editor-v2' | '/login' | '/layout/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/designer' | '/editor-v2' | '/login' | '/layout'
  id: '__root__' | '/' | '/designer' | '/editor-v2' | '/login' | '/layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DesignerRoute: typeof DesignerRoute
  EditorV2Route: typeof EditorV2Route
  LoginRoute: typeof LoginRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor-v2': {
      id: '/editor-v2'
      path: '/editor-v2'
      fullPath: '/editor-v2'
      preLoaderRoute: typeof EditorV2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer': {
      id: '/designer'
      path: '/designer'
      fullPath: '/designer'
      preLoaderRoute: typeof DesignerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/layout/': {
      id: '/layout/'
      path: '/layout'
      fullPath: '/layout/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DesignerRoute: DesignerRoute,
  EditorV2Route: EditorV2Route,
  LoginRoute: LoginRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
